#ifndef MAIN_H
#define MAIN_H

#define BUILT_IN_LED_PIN 21
#define INDICATOR_LED_PIN BUILT_IN_LED_PIN 

// strip definitions
#define NUM_STRIPS 8
#define ARRAY_OF_ORDERED_STRIP_PINS {2,3,4,5,6,43,44,7}
#define MAX_PIXEL_PER_STRIP 1000
#define DEFAULT_RUN_ANIMATION_AT_START 0
#define DEFAULT_NUMBER_OF_PIXELS_AT_START 10
#define DEFAULT_ANIMATION_INTERVAL_MS_AT_START 1000

// uart definitions
#define UART_BUFFER_SIZE 10*1024
#define UART_BAUDRATE 921600
#define UART_RX_PIN 1

#endif